#!/usr/bin/env bash

# shorthand
alias ..="cd .."
alias cd.='cd $(readlink -e .)'
alias activate="source $ACTIVATE"
alias g="git"
alias gssh="gcloud compute ssh"
alias h="hostname"
alias ipy3="ipython3"
alias ipy="ipython"
alias ls="ls --color=auto -G"
alias l1="ls -1"
alias l="ls -ltrG"
alias la="ls -a"
alias less="less -iSR"
alias lr="ls --color -ltr"
alias lg="lazygit"
alias m="micromamba"
alias ng="ngit"
alias p3="python3"
alias p="python"
alias pod="popd"
alias pud="pushd"
alias r="rg"
alias rm="rm -i"
alias sl="ls -ltra"
alias t="tmux"
alias v="nvim"
alias venv="python -m venv"
alias vi="nvim"
alias vim="nvim"
alias w="which"
alias wl="watchlogs"
alias zp="zoxide query"
