#!/usr/bin/env bash

# Do nothing in non-interactive mode
case $- in
    *i*) ;;
    *) return;;
esac

# define dirs for dotfiles
export DOTFILES=${HOME}/.config/dotfiles
export SHELL_CONFIG_DIR=${DOTFILES}/shell/
export BASH_CONFIG_DIR=${DOTFILES}/shell/bash

CUSTOM_START_PATH="${BASH_CONFIG_DIR}/custom_start.sh"
[ -f ${CUSTOM_START_PATH} ] && source ${CUSTOM_START_PATH}

[ -f ${BASH_CONFIG_DIR}/exports.sh ] && source ${BASH_CONFIG_DIR}/exports.sh
[ -f ${BASH_CONFIG_DIR}/aliases.sh ] && source ${BASH_CONFIG_DIR}/aliases.sh

CUSTOM_POST_EXPORT_PATH="${BASH_CONFIG_DIR}/custom_post_export.sh"
[ -f ${CUSTOM_POST_EXPORT_PATH} ] && source ${CUSTOM_POST_EXPORT_PATH}

CUSTOM_FUNCTIONS_PATH="${BASH_CONFIG_DIR}/custom_functions.sh"
[ -f ${CUSTOM_FUNCTIONS_PATH} ] && source ${CUSTOM_FUNCTIONS_PATH}

[ -f ${BASH_CONFIG_DIR}/functions.sh ] && source ${BASH_CONFIG_DIR}/functions.sh
[ -f ${BASH_CONFIG_DIR}/options.sh ] && source ${BASH_CONFIG_DIR}/options.sh
[ -f ${BASH_CONFIG_DIR}/tools.sh ] && source ${BASH_CONFIG_DIR}/tools.sh

CUSTOM_END_PATH="${BASH_CONFIG_DIR}/custom_end.sh"
[ -f ${CUSTOM_END_PATH} ] && source ${CUSTOM_END_PATH}

